name: Automated Preprocessing

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn numpy

      - name: Run preprocessing pipeline
        run: |
          python preprocessing/automate_AriasyahRamadhan.py

      - name: Commit dan push hasil preprocessing
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add preprocessing/titanic_preprocessing/
          git commit -m "Auto: update preprocessed dataset [skip ci]" || echo "No changes to commit"
          git push